### PR TITLE
Expose the namespaces of types via header

### PR DESCRIPTION
**Pull request by haider8645**
Hello,

we need the namespaces in the mars_smurf_loader so they can be exposed via the header.

Best,
Haider

### CODE REVIEW

**Comment by chhtz** [comment]
I would prefer not to put macros in the global namespace. Would it work for you to make these `static constexpr std::string` instead? They could be declared inside the `namespace envire`.

If these have to macros, they should at least be prefixed by `ENVIRE_` or similar.

**Comment by jliersch** [comment]
Note: `constexpr std::string` is not possible, but `char[]` should work, i. e. `constexpr char constString[] = "constString";` (cf. https://stackoverflow.com/questions/27123306/is-it-possible-to-use-stdstring-in-a-constant-expression)

**Comment by chhtz** [comment]
> Note: `constexpr std::string` is not possible

Indeed, this requires at least C++20. I'd be fine to instead use either `const static std::string` or `constexpr char[]` (https://godbolt.org/z/4n3YWacK9)

**Comment by jliersch** [comment]
Using extern and defining in cpp would be a small optimization relative to `const static string` according to 
https://stackoverflow.com/questions/73125825/is-it-correct-to-define-a-global-static-const-stdstring-in-a-header-file
At least regarding c++11

**Comment by chhtz** [comment]
Just a N.B.: This branch currently does not build with the master branch of [envire_core](https://github.com/envire/envire-envire_core.git), but requires the `mars2_new_core` or related branch. But this was the case independent of this PR, so I merged it.

**Pull request merged**
